<!DOCTYPE html>
<html class="no-js" lang="fr">

<head>
	<title>Administration de la ferme</title>

	<meta charset="utf-8">
	<meta name="description" content="Ferme de Wikis">
	<meta name="author" content="Florestan Bredow">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<?=$this->printCSS()?>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<span class="brand">Administration de la ferme</span>
			<div class="nav-collapse collapse">
				<ul class="nav">
					<li><a href="#">Liste des Wikis</a></li>
					<li><a href="#archives">Liste des Archives</a></li>
				</ul>
			</div>
			<div class="nav-collapse collapse pull-right">
				<ul class="nav">
					<li><a href="./">Retour</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>

<div class="container">
	
	<?=$this->printAlerts()?>

	<h1>Liste des wikis
		<a 	class="save btn btn-mini" href="?action=exportMailing">
			<i class="icon-list-alt"></i>
		</a>
	</h1>

	<div id="wikis" class="span12">
	<table id="listeWikis"
		class="wiki-list table table-hover table-condensed tablesorter">
		<thead>
			<tr>
				<th class="span2">Nom</th>
				<th class="span2">Créé par</th>
				<th class="span2">Créé le</th>
				<th class="span1">BD</th>
				<th class="span1">Disque</th>
				<th class="span2"></th>
			</tr>
		</thead>
		<tbody>
			<?=$this->printWikis()?>
		</tbody>
	</table>


	</div>

	<h1>Liste des archives</h1>

	<div id="archives" class="span12">
	<table id="listeArchives"
		class="wiki-list table table-hover table-condensed tablesorter">
		<thead>
			<tr>
				<th class="span4">Nom</th>
				<th class="span2">Archivé le</th>
				<th class="span1">Poid</th>
				<th class="span2"></th>
			</tr>
		</thead>
		<tbody>
			<?=$this->printArchives()?>
		</tbody>

	</table>
	</div>

	<script src="http://code.jquery.com/jquery.js"></script>
	<?=$this->printJS()?>
	<script type="text/JavaScript">
		$(document).ready(function() { 
        	$("#listeWikis").tablesorter(
        		{
        			sortList: [[0,0]],
        			headers: { 
        				5: { sorter: false }
        			}
        		}
        	); 
    	});
    	$(document).ready(function() { 
        	$("#listeArchives").tablesorter(
        		{
        			sortList: [[0,0]],
        			headers: { 
        				3: { sorter: false }
	        		}
	        	}
	        ); 
    	});  
	</script>
</div>
    
</body>
</html>