<!DOCTYPE html>
<html class="no-js" lang="fr">

<head>
	<title>Administration de la ferme</title>

	<meta charset="utf-8">
	<meta name="description" content="Ferme de Wikis">
	<meta name="author" content="Florestan Bredow">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<?=$this->printCSS()?>
	<style>
      body { padding-top: 60px; }
    </style>


	
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<span class="brand">Administration de la ferme</span>
			<div class="nav-collapse collapse">
				<ul class="nav">
					<li><a href="#">Liste des Wikis</a></li>
					<li><a href="#archives">Liste des Archives</a></li>
				</ul>
			</div>
			<div class="nav-collapse collapse pull-right">
				<ul class="nav">
					<li><a href="../">Retour</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>

<div class="container">
	
	<?=$this->printAlerts()?>

	<h1>Liste des wikis</h1>

	<div id="wikis" class="span12">
	<table class="wiki-list table table-hover table-condensed">
		<thead>
			<tr>
				<th class="span2">Nom</th>
				<th class="span4">Créé par</th>
				<th class="span2">Créé le</th>
				<th class="span2"></th>
			</tr>
		</thead>
		
		<?=$this->printWikis()?>

		</table>

	</div>

	<h1>Liste des archives</h1>

	<div id="archives" class="span12">
	<table class="wiki-list table table-hover table-condensed">
		<thead>
			<tr>
				<th class="span2">Nom</th>
				<th class="span4"></th>
				<th class="span2">Archivé le</th>
				<th class="span2"></th>
			</tr>
		</thead>
		
		<?=$this->printArchives()?>

	</table>
	</div>

	<script src="http://code.jquery.com/jquery.js"></script>
	<?=$this->printJS()?>
</div>
    
</body>
</html>