<!DOCTYPE html>
<html class="no-js" lang="fr">

<head>
	<title>Administration de la ferme</title>

	<meta charset="utf-8">
	<meta name="description" content="Ferme de Wikis">
	<meta name="author" content="Florestan Bredow">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<?=$this->printCSS()?>
	<style>
      body { padding-top: 60px; }
    </style>


	
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<span class="brand">Administration de la ferme</span>
			<div class="nav-collapse collapse">
				<ul class="nav">
					<li><a href="#">Liste des Wikis</a></li>
					<li><a href="#archives">Liste des Archives</a></li>
				</ul>
			</div>
			<div class="nav-collapse collapse pull-right">
				<ul class="nav">
					<li><a href="../">Retour</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>

<div class="container">
	
	<?=$this->printAlerts()?>

	<h1>Liste des wikis</h1>

	<div id="wikis" class="span12">
	<table class="wiki-list table table-hover table-condensed">
		<thead>
			<tr>
				<th>Nom</th>
				<th>Créateur</th>
				<th>Date de création</th>
				<th></th>
			</tr>
		</thead>
		<?php 
			$this->ferme->resetIndex();
			do {
			$infos = $this->ferme->getCurWikiInfos(); 
		?>	<tr>
			<td><?php print($infos['name']); ?></td>
			<td> 
				<a href="mailto:<?php print($infos['mail']); ?>">
					<?php print($infos['mail']); ?>
				</a>
			</td>
			<td><?php print(date("Y-m-j H:i", $infos['date'])); ?></td>
			<td>
				<a 	class="save btn btn-mini" target="_blank"
					href="<?php print($infos['url']); ?>">
					<i class=" icon-eye-open"></i>
				</a>
				<a 	class="save btn btn-mini btn-success" 
					href="?action=save&name=<?php print($infos['name']); ?>">
					<i class="icon-circle-arrow-down icon-white"></i>
				</a>
				<a 	class="delete btn btn-mini btn-danger" 
					href="?action=delete&name=<?php print($infos['name']); ?>">
					<i class="icon-trash icon-white"></i>
				</a> 
			</td>
		</tr>
	<?php 
			} while($this->ferme->getNextWiki()); 
		?></table>

	</div>

	<h1>Liste des archives</h1>

	<div id="archives" class="span12">

	</div>

	<script src="http://code.jquery.com/jquery.js"></script>
	<?=$this->printJS()?>
</div>
    
</body>
</html>