<tr>
	<td><?=$infos['name']?></td>
	<td><?=date("Y-m-d H:i", $infos['date'])?></td>
	<td>
		<span class="pull-right">
			<?=number_format($infos['size']/1024,2)?> Mo
		</span>
	</td>
	<td>
		<div class="btn-group  pull-right">
			<a 	class="save btn btn-mini"
				href="<?=$infos['url']?>">
				<i class="icon-download-alt"></i>
			</a>
			<a class="save btn btn-mini btn-primary" 
				href="?action=restore&name=<?=$infos['filename']?>">
				<i class="icon-circle-arrow-up icon-white"></i> 
			</a>
			<a 	class="delete btn btn-mini btn-danger "
				onclick="return(confirm('Êtes-vous sûr de vouloir supprimer l\'archive : <?=$infos['filename']?> ?'));" 
				href="?action=deleteArchive&name=<?=$infos['filename']?>">
				<i class="icon-trash icon-white"></i>
			</a>
		</div>
	</td>
</tr>